include: 
  - package:flutter_lints/flutter.yaml
  - package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    inference_failure_on_function_invocation: ignore
    cascade_invocations: ignore
  exclude:
    - build/**
    - lib/**.g.dart
    - lib/generated/**
    - lib/di/*.config.dart
    - test/**/*.mocks.dart
    - /**.md

formatter:
  trailing_commas: automate

linter:
  rules:
    discarded_futures: false
    sort_pub_dependencies: false
    prefer_asserts_with_message: false
    avoid_catches_without_on_clauses: false
    directives_ordering: false
    public_member_api_docs: false
    prefer_constructors_over_static_methods: false
    omit_local_variable_types: false
